### ISSUE TITLE
Face Unlock via swipe doesn't work

### ISSUE THREAD

**Issue by jinetty** [crdroidandroid/android_packages_apps_crDroidSettings#1002]
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/13.0/res/values/cr_strings.xml#L855 i guess this string didn't applied. I did clean flash and add face unlock, then applied swipe rule and it was working as expected but when i rebooted my phone, it scans when i open my screen even rule is selected.
https://user-images.githubusercontent.com/64617882/209698756-c771c727-c4c8-448f-9b67-a6922891ec93.mp4

**Comment by gwolf2u** [comment]
while I agree of said bug, do use issue_tracker please
https://github.com/crdroidandroid/issue_tracker/issues/new/choose

**Comment by jinetty** [comment]
This issue page requires to check "I've checked device is officially supported." but my device is not officially supported, i've ported myself.
