### ISSUE TITLE
Feature request: Quick Settings redesign like in Dot OS 6.0

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#1022]
If something like this will be added to the crDroid
https://github.com/DotOS/android_frameworks_base/commit/744beb58da1eeb9ce7fdde52edf98a5f8e018648
This would make crDroid the best custom ROM of all, since there is no ROM, that has such customization features and such devices support. It would be an amazing combo.
![FcO1mOSaIAApxtD](https://user-images.githubusercontent.com/25207200/216690283-f9f07d08-c4c8-459d-972e-bdfa8121548e.jpeg)

**Comment by gwolf2u** [comment]
for now this is not on our focus list
