### ISSUE TITLE
Proposal for logo change 

### ISSUE THREAD

**Issue by minax007** [crdroidandroid/android_packages_apps_crDroidSettings#1036]
Hi everybody, 

I like crDroid a lot but there is something that is disturbing about it. 

It is the logo. 

The eye of horus is a symbol of paganism. 

https://en.wikipedia.org/wiki/Eye_of_Horus

I would appreciate if this pagan symbol would get replaced by something neutral.

**Comment by gwolf2u** [comment]
https://crdroid.net/#faq
![Screenshot_20230330-061459~2](https://user-images.githubusercontent.com/877292/228719444-a36b947b-74a1-4018-b3eb-142f61aa4aeb.png)
