### ISSUE TITLE
Bedtime mode

### ISSUE THREAD

**Issue by yoyoda2048** [crdroidandroid/android_packages_apps_crDroidSettings#1037]
Hi
Fresh install on my REDMI NOTE 8 Ginkgo CRDROID9.2 + NikGAPPS core = everything is OK.
I installed Google Digital Wellbeing App to use Bedtime Mode then when the time comes it switches on but my phone doesn't turn on white and black and do not disturb modes like it should.
Did I miss something ?
Thank you for your work on this ROM !
Regards

**Comment by gwolf2u** [comment]
3rd party apps
