### ISSUE TITLE
You may ban me but this isn't fixed.

### ISSUE THREAD

**Issue by KoremuMekuro** [crdroidandroid/android_packages_apps_crDroidSettings#1042]
This isn't fixed.On poco f3 update was only a day ago.And in the commit there are still the same options from this 9.3 update and not from march 31st 9.3 or 9.2 and earlier.Or maybe I have to downgrade and show that settings are changed and that they are producing bad results in dark mode.
![Screenshot_20230407-192142_Settings](https://user-images.githubusercontent.com/125179297/230643193-3c0dfd91-fcf6-480b-ac0f-335eee9d402b.png)

**Comment by gwolf2u** [comment]
why not wait for next build and check

**Comment by KoremuMekuro** [comment]
> why not wait for next build and check

Cuz this build that I recived yesterday is done after those commits that changed settings to this 'thing'.
