### ISSUE TITLE
提高键盘高度

### ISSUE THREAD

**Issue by monklamn** [crdroidandroid/android_packages_apps_crDroidSettings#1076]
我是一个中国的网友，很喜欢crDroid和LineageOS。于是在redmi9上输入了LineageOS，在redmi note8pro 上刷入了crdrdoi 9.10。两台手机都安装了2个输入法，使用过程中发现了下面的问题：
![image](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/assets/110436640/0d1fcf41-db57-4b91-9c39-47ce8e4a12f9)

LineageOS 的键盘会自动抬高，右下角可以切换输入法。
crDroid 的键盘没有抬高，没有切换输入的按钮。
请问：能否处理一下？跟LineageOS一样？

**Comment by gwolf2u** [comment]
bad place to report any kind of issues

**Comment by monklamn** [comment]
> bad place to report any kind of issues

so can you tell me  which part can i report this issues please? thanks

**Comment by gwolf2u** [comment]
issue_tracker repo
