### ISSUE TITLE
Brown Theme not working

### ISSUE THREAD

**Issue by AbhilashKannankara** [crdroidandroid/android_packages_apps_crDroidSettings#1124]
![Screenshot_20240207-071716_Wallpaper_and_style 1](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/assets/80334164/32da66ff-d85c-4b5e-8b0c-197deac7ae6f)
when apply brown theme according to the wallpaper,it applies blue theme or default theme,theme icons also not works according to the applied brown theme.Not using pixel launcher or there stuffs,all set as default

**Comment by gwolf2u** [comment]
please use issue tracket
