### ISSUE TITLE
Feature request: Battery idle mode

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [crdroidandroid/android_packages_apps_crDroidSettings#1174]
It would be even better for battery health if the "Charge limit control" setting had a toggle to enable battery idle mode. ACC has this feature:
> Battery idle mode, also called "standby mode" or "charging bypass", is the ability of running off the charger, as if the battery were disconnected from the device.

Right now it seems like when the charging is stopped, it just uses the battery power until the battery percentage gets low enough that charging should stop again. This would cause unnecessary charge cycles on the battery.

Also, how does the "Charge limit control" currently work and how does it compare to ACC?

**Comment by gwolf2u** [comment]
charging is stopped when limit is reached and will resume when gets lower that limit
not perfect, but how it is
