### ISSUE TITLE
Choose a custom editor app for screenshot notification edit button [2/2] ? 

### ISSUE THREAD

**Issue by Razziell** [crdroidandroid/android_packages_apps_crDroidSettings#211]
There is not enough second patch to be able to choose a third-party application for screenshot editing, as there is not enough editing capability on the screenshot. In the RR analog - https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/e81a0de9b163d200680aff4383bb04a94f571ce6#diff-5fd1f041de9a29b1a8d7a90a537c28b1

**Comment by Razziell** [comment]
https://gist.github.com/Razziell/db51f0f72019bb7600aeeb24ee04e8fa
![photo_2018-05-09_12-43-10](https://user-images.githubusercontent.com/7115882/39808065-a00a3b74-5386-11e8-8fb5-fb50b909cd87.jpg)
![photo_2018-05-09_12-43-20](https://user-images.githubusercontent.com/7115882/39808066-a029205c-5386-11e8-921f-21875ea4684e.jpg)
![photo_2018-05-09_12-43-26](https://user-images.githubusercontent.com/7115882/39808067-a0498d24-5386-11e8-996a-58f457bc020c.jpg)

**Comment by neobuddy89** [comment]
Yep, this was left given complexity of second patch. Will add in 4.3

**Comment by Razziell** [comment]
Update 
https://gist.github.com/Razziell/153edbf3a88fc404f8fd1b876f9d589e
![photo_2018-05-12_17-16-18](https://user-images.githubusercontent.com/7115882/39958184-3ab884cc-5608-11e8-8b94-96acdcd1c1e0.jpg)
