### ISSUE TITLE
donate.xml breaks compile...

### ISSUE THREAD

**Issue by Ziggy815** [crdroidandroid/android_packages_apps_crDroidSettings#268]
packages/apps/crDroidSettings/res/xml/donate.xml:22: error: resource drawable/ic_account_circle (aka com.android.settings:drawable/ic_account_circle) not found.
packages/apps/crDroidSettings/res/xml/donate.xml:29: error: resource drawable/ic_account_circle (aka com.android.settings:drawable/ic_account_circle) not found.

android_packages_apps_crDroidSettings/res/drawable/ic_account_circle.xml - seems just be missing in 8.1 branch

**Comment by gwolf2u** [comment]
fixed https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/fced3998b863854da3cfa96749df11b5d894cd93
