### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by Valdex** [crdroidandroid/android_packages_apps_crDroidSettings#271]
When im change gray to amoled, setting crash
RedMi 5 Plus crDroid 4.6
![screenshot__20180918-083121](https://user-images.githubusercontent.com/30376783/45666328-c2b6b680-bb1d-11e8-9b55-ec2d2448c56a.png)
![screenshot__20180918-083118](https://user-images.githubusercontent.com/30376783/45666322-bdf20280-bb1d-11e8-9783-78a0cf0486b7.png)

**Comment by Valdex** [comment]
Where i can find log?

**Comment by gwolf2u** [comment]
install MatLog from PlayStore, open it and start a log then go to dedicated settings and let it crash
return to MatLog and stop logging 
submit the file here or on device forum

**Comment by Valdex** [comment]
[2018-09-18-18-47-42.txt](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/files/2393465/2018-09-18-18-47-42.txt)

**Comment by Valdex** [comment]
@gwolf2u

**Comment by gwolf2u** [comment]
@neobuddy89 
Willing to have a look?

**Comment by gwolf2u** [comment]
@root2raj does this happen to you?

**Comment by root2raj** [comment]
Don't know about if it happened in any older version. But on the latest v4.6.1, I can confirm it works fine.

**Comment by gwolf2u** [comment]
@Valdex please update to latest version
