### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ieprst** [crdroidandroid/android_packages_apps_crDroidSettings#360]
59% 57367/95627] AAPT2 compile /home...tings/res/values-pt-rPT/cr_strings.xml
FAILED: /home/alex/crDroid/out/target/common/obj/APPS/Settings_intermediates/flat-res/packages/apps/crDroidSettings/res/values-pt-rPT_cr_strings.arsc.flat 
/bin/bash -c "/home/alex/crDroid/out/host/linux-x86/bin/aapt2 compile -o /home/alex/crDroid/out/target/common/obj/APPS/Settings_intermediates/flat-res/packages/apps/crDroidSettings/res/ --pseudo-localize --legacy packages/apps/crDroidSettings/res/values-pt-rPT/cr_strings.xml"
packages/apps/crDroidSettings/res/values-pt-rPT/cr_strings.xml:0: error: xml parser error: not well-formed (invalid token).
[ 59% 57370/95627] AAPT2 compile /home...tings/res/values-ro-rRO/cr_strings.xml

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/pull/359
