### ISSUE TITLE
toogles

### ISSUE THREAD

**Issue by Henry2o1o** [crdroidandroid/android_packages_apps_crDroidSettings#584]
Hello, where can I change the space between the lines?
In a xml (dimens)?

![image](https://user-images.githubusercontent.com/6131799/81533853-3d71bc80-9367-11ea-95bb-940dba043e19.png)

**Comment by Henry2o1o** [comment]
![photo_2020-05-11_09-20-05](https://user-images.githubusercontent.com/6131799/81536335-a9562400-936b-11ea-94cd-bc22ace15306.jpg)

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android_frameworks_base/blob/10.0/packages/SystemUI/res/values/dimens.xml#L453
