### ISSUE TITLE
[Feature request] Allow custom actions for long presses/double taps on navigation buttons

### ISSUE THREAD

**Issue by panaut0lordv** [crdroidandroid/android_packages_apps_crDroidSettings#59]
Use case: as for know only "Long press to kill" is available for "Back" button, while OxygenOS allows custom values, among which there is "Switch to previous task". That is one feature of Windows Mobile that I think is absolutely great, as it allows for quick switching between two apps without opening "Recents" screen.

How it works: Only "Home" can have custom long press and double tap actions.
How it should be (IMHO): "Back and Recents" should also have the option to customise those.

Cheers,
Mike

**Comment by neobuddy89** [comment]
Settings > crDroid Settings > Navigation > Smartbar settings > Toggle button editor
Longpress nav key > Actions
Assign action
Tap X to exit editor mode.

**Comment by panaut0lordv** [comment]
I am very sorry mate, but what about those of us that do NOT have onscreen buttons (OnePlus 3T)?
Home button can be customised so why not the back button? ;)

Cheers,
Mike

**Comment by neobuddy89** [comment]
Sorry, I dont have device with HW keys to dev and test.

**Comment by panaut0lordv** [comment]
Please find attached my very rough "patch", although I have no idea if I should recompile whole crDroid or only crDroidSettings.apk would be fine.
Anyway I am willing to test and debug, so feel free to get in touch (my e-mail is in profile) if you would like to assist me in getting it working.

Cheers,
Mike

[backlongpress_v1.patch.txt](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/files/994146/backlongpress_v1.patch.txt)

**Comment by neobuddy89** [comment]
@soubhik-khan Can you please look into this?

**Comment by neobuddy89** [comment]
@panaut0lordv This requires changes in frameworks_base as well. Not sure if you can add with single patch.

@soubhik-khan please try if we have complete set of patches.
