### ISSUE TITLE
Add Reset battery stats

### ISSUE THREAD

**Issue by Razziell** [crdroidandroid/android_packages_apps_crDroidSettings#591]
https://github.com/syberia-project/platform_frameworks_base/commit/5dba075af614e6023edf2cec0067870dd31038df
https://github.com/syberia-project/platform_packages_apps_Settings/commit/b5d023f5dcf7cee193d8bcc56324ebe2b1eb1a22

**Comment by gwolf2u** [comment]
please submit pull request
