### ISSUE TITLE
Pixel face unlock. 

### ISSUE THREAD

**Issue by lividhen** [crdroidandroid/android_packages_apps_crDroidSettings#641]
I know I really should leave a pull request, but I really have no idea how I would get this to work with crdroid settings 😅. If somebody with more knowledge would like to implement this, that could be cool. 
https://github.com/PixelExperience/packages_apps_Settings/commit/35ff6c59a8f9a216cd5d819a99f6b037a1c80654

**Comment by gwolf2u** [comment]
it's already implemented in official devices

**Comment by lividhen** [comment]
Oh! Really!? Is this only for official devices? Or is this just a requirement for it to be official? If it's the second could you link to the commit? It doesn't seem to be working on my device.

**Comment by gwolf2u** [comment]
It's only for official devices as of now

**Comment by lividhen** [comment]
Okay thanks for the info!
