### ISSUE TITLE
ambient display issue

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#705]
The ambient display code of crdroid always fails. I have mentioned this problem, but you always said that this is because the sensor of OnePlus is too close to the screen, causing the ambient display to fail. I have used the ambient display settings and crdroid of rr and havoc.  The ambient display is different, but in the two roms of rr and havoc, the waved screen and pocket wake-up can work normally and will not stop working after a period of use. The above is the ambient display setting of havoc11‌‌

The maintainer of 5t also tried to modify the doze display setting code to a style similar to havoc. At that time, the ambient display of crdroid did work normally and would not fail, but for unknown reasons, neobody was only used once, and all subsequent builds  All changed to the previous ambient display style. After that, the wave and pocket wakeup didn’t work properly. I hope you don’t ignore this issue. I am waiting for you to fix this issue and return to crdroid7.2
![Screenshot_20210128-203958978](https://user-images.githubusercontent.com/24615844/107108977-4c928600-6877-11eb-96fc-afca3dc1d673.jpg)

**Comment by gwolf2u** [comment]
as issue is more or less caused by different hardware or implementation then other crDroid devices have, we will review this at a later time if possible
