### ISSUE TITLE
Navigation bar visibility is reset after reboot

### ISSUE THREAD

**Issue by jkommeren** [crdroidandroid/android_packages_apps_crDroidSettings#786]
Hope this is the right place

Crdroid offers toggle for Navigation Bar visibility under Navigation. When I turn it off navigation bar is hidden. Works splendidly!

Then when I reboot the nav bar is visible again. When I go to settings the toggle is still off. I then need to turn it on and off again for it to be hidden again.

Issue has been present since I've been using crdroid: 7.6 up to 7.9
Using a OnePlus 7 pro.

It's just a little annoying and would be nice if there's an easy fix for it

**Comment by Orel6505** [comment]
7.9 not exist yet

**Comment by Orel6505** [comment]
use magisk module - Fullscreen/Immersive Gestures (Q-S)

**Comment by jkommeren** [comment]
Yes I meant 7.8 😅 thanks I'll use that! Are you planning on fixing it though? Out of interest.

**Comment by Orel6505** [comment]
I am not from crDroid team lol

**Comment by xNombre** [comment]
@neobuddy89 You should take a look, you recently changed sth in navbar 
https://github.com/crdroidandroid/android_frameworks_base/commit/b30c9063b48603a0bec863698d96845740a4ca72
