### ISSUE TITLE
Feature request: Add more rounded icon shape in settings

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#942]
Feature request: add one more icon shape, more rounded than the existing one. This icon shape present in Google Play, OOS, MIUI and other custom or official ROMs. It would be cool to see this style in crDroid
![IMG_20220710_232130_614](https://user-images.githubusercontent.com/25207200/178161083-6cfe9254-af31-42b6-b4b3-24ca473af3ac.jpg)
![IMG_20220710_231523](https://user-images.githubusercontent.com/25207200/178161092-1ced4f9a-e308-4807-bf80-1cf4a2e64f64.jpg)

**Comment by neobuddy89** [comment]
which other roms?

**Comment by lordgregorymsk** [comment]
Color OS
