### ISSUE TITLE
Feature request: Add A11 style Quick Settings option

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#944]
Feature request: could team add A11 style Quick Settings switcher (option)? Something like that https://github.com/neobuddy89/derp_base/commit/34a7aa4453acc621cd98a48e8bdd46770f6bf0cd
If it will be difficult to add, and this feature, in your opinion, will be of no interest to crDroid users, then close this request please, and thank you anyway for reviewing this request.
![FPrnS03VUAEzcyt](https://user-images.githubusercontent.com/25207200/179230894-2b67826e-6b5d-4da6-807f-5fc05b7b8433.jpg)

**Comment by Saviour5** [comment]
Yes , option to a11 kinda quick settings looks cool ,and AppLock features in settings - security & not in launcher will really helpful , if possible please consider these , and thank your work , this rom is damn good even with plenty of customisations

**Comment by Louis2747** [comment]
In my opinion, the quick settings are the biggest problem with A12, so this would be very cool.

**Comment by GalaxyNight** [comment]
cool

**Comment by gwolf2u** [comment]
as of this time, it's not possible to implement a toggle for QS style
unless we can enable toggle based style, we don't want to move away from AOSP Android 12 style

**Comment by cigneve** [comment]
CorvusOS has some kind of qs style settings is it possible to implement something like that?
