### ISSUE TITLE
Translation issue in DeviceSettings

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#954]
https://github.com/crdroidandroid/android_device_oneplus_sm8150-common/blob/12.1/DeviceSettings/res/values-ru/cr_strings.xml
In line 43     <string name="notification_slider_category_title">Боковой переклячатель уведомлений</string>

Must be       <string name="notification_slider_category_title">Боковой переключатель уведомлений</string>

**Comment by ShevT** [comment]
Исправлено!
Благодарю.
