### ISSUE TITLE
Feature request: Add row customization for QS layout

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_crDroidSettings#958]
Feature request: could team add row customization for QS layout? Ex. Instead of 4x4 user can set 4x3 or 3x2 etc.
If it will be difficult to add, and this feature, in your opinion, will be of no interest to crDroid users, then close this request please, and thank you anyway for reviewing this request.

**Comment by gwolf2u** [comment]
added https://crdroid.net/blog/2022-08-30-changelog-august-30
